export type FnCategory =
  | 'Math'
  | 'Logical'
  | 'Text'
  | 'Date & Time'
  | 'Lookup'
  | 'Conditional'
  | 'Statistical'
  | 'Financial'
  | 'Info';

export interface FnDef {
  name: string;
  syntax: string;
  desc: string;
  descKh: string;
  example: string;
  category: FnCategory;
  args: { name: string; desc: string; optional?: boolean }[];
}

export const FUNCTION_REGISTRY: FnDef[] = [
  // ---- Math ----
  { name: 'SUM', category: 'Math', syntax: 'SUM(number1, [number2, ...])', desc: 'Adds all numbers in a range.', descKh: 'បូកសរុបលេខទាំងអស់ក្នុងជួរ', example: '=SUM(A1:A10)', args: [{ name: 'number1', desc: 'First number or range' }, { name: 'number2', desc: 'Additional numbers or ranges', optional: true }] },
  { name: 'AVERAGE', category: 'Math', syntax: 'AVERAGE(number1, [number2, ...])', desc: 'Returns the arithmetic mean.', descKh: 'ត្រឡប់មធ្យមភាគនព្វន្ធ', example: '=AVERAGE(B1:B20)', args: [{ name: 'number1', desc: 'First number or range' }, { name: 'number2', desc: 'Additional numbers', optional: true }] },
  { name: 'MIN', category: 'Math', syntax: 'MIN(number1, [number2, ...])', desc: 'Returns the smallest value.', descKh: 'ត្រឡប់តម្លៃតូចបំផុត', example: '=MIN(A1:A10)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'MAX', category: 'Math', syntax: 'MAX(number1, [number2, ...])', desc: 'Returns the largest value.', descKh: 'ត្រឡប់តម្លៃធំបំផុត', example: '=MAX(A1:A10)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'COUNT', category: 'Math', syntax: 'COUNT(value1, [value2, ...])', desc: 'Counts cells that contain numbers.', descKh: 'រាប់ចំនួនក្រឡាដែលមានតម្លៃជាលេខ', example: '=COUNT(A1:A10)', args: [{ name: 'value1', desc: 'First value or range' }] },
  { name: 'COUNTA', category: 'Math', syntax: 'COUNTA(value1, [value2, ...])', desc: 'Counts non-empty cells.', descKh: 'រាប់ចំនួនក្រឡាដែលមិនទទេ', example: '=COUNTA(A1:A10)', args: [{ name: 'value1', desc: 'First value or range' }] },
  { name: 'PRODUCT', category: 'Math', syntax: 'PRODUCT(number1, [number2, ...])', desc: 'Multiplies all numbers together.', descKh: 'គុណលេខទាំងអស់ជាមួយគ្នា', example: '=PRODUCT(A1:A5)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'SUMPRODUCT', category: 'Math', syntax: 'SUMPRODUCT(array1, [array2, ...])', desc: 'Multiplies corresponding elements and sums the results.', descKh: 'គុណធាតុដែលត្រូវគ្នា រួចបូកសរុប', example: '=SUMPRODUCT(A1:A5, B1:B5)', args: [{ name: 'array1', desc: 'First array' }, { name: 'array2', desc: 'Second array', optional: true }] },
  { name: 'ROUND', category: 'Math', syntax: 'ROUND(number, digits)', desc: 'Rounds a number to specified decimal places.', descKh: 'បង្គត់ចំនួនទៅកន្លះបន្ទាត់ដែលបានកំណត់', example: '=ROUND(3.14159, 2)', args: [{ name: 'number', desc: 'The number to round' }, { name: 'digits', desc: 'Number of decimal places' }] },
  { name: 'ROUNDUP', category: 'Math', syntax: 'ROUNDUP(number, digits)', desc: 'Rounds a number up, away from zero.', descKh: 'បង្គត់ចំនួនឡើងលើ', example: '=ROUNDUP(3.141, 2)', args: [{ name: 'number', desc: 'Number to round up' }, { name: 'digits', desc: 'Decimal places' }] },
  { name: 'ROUNDDOWN', category: 'Math', syntax: 'ROUNDDOWN(number, digits)', desc: 'Rounds a number down, toward zero.', descKh: 'បង្គត់ចំនួនចុះក្រោម', example: '=ROUNDDOWN(3.999, 1)', args: [{ name: 'number', desc: 'Number to round down' }, { name: 'digits', desc: 'Decimal places' }] },
  { name: 'ABS', category: 'Math', syntax: 'ABS(number)', desc: 'Returns the absolute value.', descKh: 'ត្រឡប់តម្លៃដាច់ខាត (ជានិជ)', example: '=ABS(-5)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'SQRT', category: 'Math', syntax: 'SQRT(number)', desc: 'Returns the positive square root.', descKh: 'ត្រឡប់ឫសសក្វ័រ (ឫស២)', example: '=SQRT(16)', args: [{ name: 'number', desc: 'The number (must be ≥ 0)' }] },
  { name: 'POWER', category: 'Math', syntax: 'POWER(number, power)', desc: 'Returns number raised to a power.', descKh: 'គណនាការលើកស្វ័យគុណ (e.g. 2^10)', example: '=POWER(2, 10)', args: [{ name: 'number', desc: 'The base' }, { name: 'power', desc: 'The exponent' }] },
  { name: 'MOD', category: 'Math', syntax: 'MOD(number, divisor)', desc: 'Returns the remainder after division.', descKh: 'ត្រឡប់សំណល់ក្រោយការចែក', example: '=MOD(10, 3)', args: [{ name: 'number', desc: 'The dividend' }, { name: 'divisor', desc: 'The divisor' }] },
  { name: 'INT', category: 'Math', syntax: 'INT(number)', desc: 'Rounds down to the nearest integer.', descKh: 'បង្គត់ចុះទៅចំនួនគត់ណិតបំផុត', example: '=INT(3.9)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'TRUNC', category: 'Math', syntax: 'TRUNC(number, [digits])', desc: 'Truncates a number toward zero.', descKh: 'កាត់ចំនួនភាគរយ ដោយមិនបង្គត់', example: '=TRUNC(3.9)', args: [{ name: 'number', desc: 'The number' }, { name: 'digits', desc: 'Decimal places to keep', optional: true }] },
  { name: 'CEILING', category: 'Math', syntax: 'CEILING(number, significance)', desc: 'Rounds up to the nearest multiple.', descKh: 'បង្គត់ឡើងទៅទ្វេរអព្ភើយដ៏ណិតបំផុត', example: '=CEILING(4.1, 0.5)', args: [{ name: 'number', desc: 'The number' }, { name: 'significance', desc: 'Multiple to round to' }] },
  { name: 'FLOOR', category: 'Math', syntax: 'FLOOR(number, significance)', desc: 'Rounds down to the nearest multiple.', descKh: 'បង្គត់ចុះទៅទ្វេរអព្ភើយដ៏ណិតបំផុត', example: '=FLOOR(4.9, 0.5)', args: [{ name: 'number', desc: 'The number' }, { name: 'significance', desc: 'Multiple to round to' }] },
  { name: 'ODD', category: 'Math', syntax: 'ODD(number)', desc: 'Rounds up to the nearest odd integer.', descKh: 'បង្គត់ឡើងទៅចំនួនសេសណិតបំផុត', example: '=ODD(4)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'EVEN', category: 'Math', syntax: 'EVEN(number)', desc: 'Rounds up to the nearest even integer.', descKh: 'បង្គត់ឡើងទៅចំនួនគូណិតបំផុត', example: '=EVEN(3)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'SIGN', category: 'Math', syntax: 'SIGN(number)', desc: 'Returns 1, 0, or -1 based on the sign.', descKh: 'ត្រឡប់ 1, 0, ឬ -1 តាមសញ្ញា', example: '=SIGN(-5)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'GCD', category: 'Math', syntax: 'GCD(number1, [number2, ...])', desc: 'Returns the greatest common divisor.', descKh: 'ត្រឡប់ម.ស.ត. (ផ្នែកធំសាមញ្ញបំផុត)', example: '=GCD(12, 8)', args: [{ name: 'number1', desc: 'First number' }] },
  { name: 'LCM', category: 'Math', syntax: 'LCM(number1, [number2, ...])', desc: 'Returns the least common multiple.', descKh: 'ត្រឡប់ ម.ស.ទ. (ច្រើនតូចសាមញ្ញបំផុត)', example: '=LCM(4, 6)', args: [{ name: 'number1', desc: 'First number' }] },
  { name: 'LOG', category: 'Math', syntax: 'LOG(number, [base])', desc: 'Returns the logarithm of a number.', descKh: 'ត្រឡប់លោហករីតរបស់ចំនួន', example: '=LOG(1000, 10)', args: [{ name: 'number', desc: 'Positive number' }, { name: 'base', desc: 'Logarithm base (default 10)', optional: true }] },
  { name: 'LOG10', category: 'Math', syntax: 'LOG10(number)', desc: 'Returns the base-10 logarithm.', descKh: 'ត្រឡប់លោហករីតមូលដ្ឋាន 10', example: '=LOG10(100)', args: [{ name: 'number', desc: 'Positive number' }] },
  { name: 'LN', category: 'Math', syntax: 'LN(number)', desc: 'Returns the natural logarithm.', descKh: 'ត្រឡប់លោហករីតធម្មជាតិ (base e)', example: '=LN(2.71828)', args: [{ name: 'number', desc: 'Positive number' }] },
  { name: 'EXP', category: 'Math', syntax: 'EXP(number)', desc: 'Returns e raised to the power.', descKh: 'ត្រឡប់ e លើក e^n', example: '=EXP(1)', args: [{ name: 'number', desc: 'The exponent' }] },
  { name: 'PI', category: 'Math', syntax: 'PI()', desc: 'Returns π (3.14159…).', descKh: 'ត្រឡប់តម្លៃ π ≈ 3.14159', example: '=PI()', args: [] },
  { name: 'RAND', category: 'Math', syntax: 'RAND()', desc: 'Returns a random number between 0 and 1.', descKh: 'ត្រឡប់ចំនួនចៃដន្យ 0 ដល់ 1', example: '=RAND()', args: [] },
  { name: 'RANDBETWEEN', category: 'Math', syntax: 'RANDBETWEEN(bottom, top)', desc: 'Returns a random integer between two values.', descKh: 'ត្រឡប់ចំនួនគត់ចៃដន្យរវាងពីរតម្លៃ', example: '=RANDBETWEEN(1, 100)', args: [{ name: 'bottom', desc: 'Minimum value' }, { name: 'top', desc: 'Maximum value' }] },
  { name: 'FACT', category: 'Math', syntax: 'FACT(number)', desc: 'Returns the factorial of a number.', descKh: 'ត្រឡប់ Factorial (n!)', example: '=FACT(5)', args: [{ name: 'number', desc: 'Non-negative integer' }] },
  { name: 'COMBIN', category: 'Math', syntax: 'COMBIN(n, k)', desc: 'Returns the number of combinations C(n,k).', descKh: 'ត្រឡប់ចំនួនការរួមបញ្ចូល C(n,k)', example: '=COMBIN(10, 3)', args: [{ name: 'n', desc: 'Total items' }, { name: 'k', desc: 'Items chosen' }] },
  { name: 'FIXED', category: 'Math', syntax: 'FIXED(number, [decimals], [no_commas])', desc: 'Formats a number as text with commas.', descKh: 'ធ្វើទ្រង់ទ្រាយចំនួនជាអត្ថបទដោយមានសញ្ញាក្បៀស', example: '=FIXED(1234.567, 2)', args: [{ name: 'number', desc: 'The number' }, { name: 'decimals', desc: 'Decimal places (default 2)', optional: true }, { name: 'no_commas', desc: 'TRUE to omit commas', optional: true }] },
  { name: 'ISODD', category: 'Math', syntax: 'ISODD(number)', desc: 'Returns TRUE if number is odd.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើចំនួនជាសេស', example: '=ISODD(3)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'ISEVEN', category: 'Math', syntax: 'ISEVEN(number)', desc: 'Returns TRUE if number is even.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើចំនួនជាគូ', example: '=ISEVEN(4)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'SIN', category: 'Math', syntax: 'SIN(angle)', desc: 'Returns the sine of an angle (radians).', descKh: 'ត្រឡប់ sine (មុំជា radians)', example: '=SIN(PI()/2)', args: [{ name: 'angle', desc: 'Angle in radians' }] },
  { name: 'COS', category: 'Math', syntax: 'COS(angle)', desc: 'Returns the cosine of an angle (radians).', descKh: 'ត្រឡប់ cosine (មុំជា radians)', example: '=COS(0)', args: [{ name: 'angle', desc: 'Angle in radians' }] },
  { name: 'TAN', category: 'Math', syntax: 'TAN(angle)', desc: 'Returns the tangent of an angle (radians).', descKh: 'ត្រឡប់ tangent (មុំជា radians)', example: '=TAN(PI()/4)', args: [{ name: 'angle', desc: 'Angle in radians' }] },
  { name: 'ASIN', category: 'Math', syntax: 'ASIN(number)', desc: 'Returns the arcsine in radians.', descKh: 'ត្រឡប់ arcsine ជា radians', example: '=ASIN(1)', args: [{ name: 'number', desc: 'Value between -1 and 1' }] },
  { name: 'ACOS', category: 'Math', syntax: 'ACOS(number)', desc: 'Returns the arccosine in radians.', descKh: 'ត្រឡប់ arccosine ជា radians', example: '=ACOS(0)', args: [{ name: 'number', desc: 'Value between -1 and 1' }] },
  { name: 'ATAN', category: 'Math', syntax: 'ATAN(number)', desc: 'Returns the arctangent in radians.', descKh: 'ត្រឡប់ arctangent ជា radians', example: '=ATAN(1)', args: [{ name: 'number', desc: 'The number' }] },
  { name: 'ATAN2', category: 'Math', syntax: 'ATAN2(x_num, y_num)', desc: 'Returns the arctangent of coordinates (x, y).', descKh: 'ត្រឡប់ arctangent នៃ좌标 (x, y)', example: '=ATAN2(1, 1)', args: [{ name: 'x_num', desc: 'X coordinate' }, { name: 'y_num', desc: 'Y coordinate' }] },
  { name: 'RADIANS', category: 'Math', syntax: 'RADIANS(angle)', desc: 'Converts degrees to radians.', descKh: 'បំប្លែងដឺក្រេ → radians', example: '=RADIANS(180)', args: [{ name: 'angle', desc: 'Angle in degrees' }] },
  { name: 'DEGREES', category: 'Math', syntax: 'DEGREES(angle)', desc: 'Converts radians to degrees.', descKh: 'បំប្លែង radians → ដឺក្រេ', example: '=DEGREES(PI())', args: [{ name: 'angle', desc: 'Angle in radians' }] },
  { name: 'MROUND', category: 'Math', syntax: 'MROUND(number, multiple)', desc: 'Rounds to the nearest multiple.', descKh: 'បង្គត់ទៅជិតទ្វេរអព្ភើយ', example: '=MROUND(10, 3)', args: [{ name: 'number', desc: 'The number' }, { name: 'multiple', desc: 'Multiple to round to' }] },
  { name: 'QUOTIENT', category: 'Math', syntax: 'QUOTIENT(numerator, denominator)', desc: 'Returns the integer portion of division.', descKh: 'ត្រឡប់ផ្នែកគត់នៃការចែក', example: '=QUOTIENT(10, 3)', args: [{ name: 'numerator', desc: 'Dividend' }, { name: 'denominator', desc: 'Divisor' }] },

  // ---- Logical ----
  { name: 'IF', category: 'Logical', syntax: 'IF(condition, value_if_true, [value_if_false])', desc: 'Returns one value if TRUE, another if FALSE.', descKh: 'ត្រឡប់តម្លៃខុសគ្នាតាមលក្ខខណ្ឌ', example: '=IF(A1>10, "big", "small")', args: [{ name: 'condition', desc: 'Expression that evaluates to TRUE or FALSE' }, { name: 'value_if_true', desc: 'Value when condition is TRUE' }, { name: 'value_if_false', desc: 'Value when condition is FALSE', optional: true }] },
  { name: 'IFS', category: 'Logical', syntax: 'IFS(cond1, val1, [cond2, val2, ...])', desc: 'Checks multiple conditions, returns value for first TRUE.', descKh: 'ពិនិត្យលក្ខខណ្ឌច្រើន ត្រឡប់តម្លៃទីមួយដែល TRUE', example: '=IFS(A1>90,"A",A1>80,"B",TRUE,"C")', args: [{ name: 'cond1', desc: 'First condition' }, { name: 'val1', desc: 'Value if cond1 is TRUE' }] },
  { name: 'AND', category: 'Logical', syntax: 'AND(logical1, [logical2, ...])', desc: 'Returns TRUE if all conditions are TRUE.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើលក្ខខណ្ឌទាំងអស់ជា TRUE', example: '=AND(A1>0, B1>0)', args: [{ name: 'logical1', desc: 'First condition' }, { name: 'logical2', desc: 'Additional conditions', optional: true }] },
  { name: 'OR', category: 'Logical', syntax: 'OR(logical1, [logical2, ...])', desc: 'Returns TRUE if any condition is TRUE.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើលក្ខខណ្ឌណាមួយជា TRUE', example: '=OR(A1="Yes", B1="Yes")', args: [{ name: 'logical1', desc: 'First condition' }] },
  { name: 'NOT', category: 'Logical', syntax: 'NOT(logical)', desc: 'Reverses the logic of its argument.', descKh: 'ត្រឡប់ TRUE → FALSE ឬ FALSE → TRUE', example: '=NOT(A1=0)', args: [{ name: 'logical', desc: 'The condition to reverse' }] },
  { name: 'XOR', category: 'Logical', syntax: 'XOR(logical1, [logical2, ...])', desc: 'Returns TRUE if an odd number of conditions are TRUE.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើចំនួនសេស TRUE', example: '=XOR(A1, B1)', args: [{ name: 'logical1', desc: 'First condition' }] },
  { name: 'IFERROR', category: 'Logical', syntax: 'IFERROR(value, value_if_error)', desc: 'Returns value_if_error if expression errors.', descKh: 'ត្រឡប់តម្លៃផ្សេងប្រសិនបើមានកំហុស', example: '=IFERROR(A1/B1, 0)', args: [{ name: 'value', desc: 'Expression to evaluate' }, { name: 'value_if_error', desc: 'Value to return on error' }] },
  { name: 'IFNA', category: 'Logical', syntax: 'IFNA(value, value_if_na)', desc: 'Returns value_if_na if expression is #N/A.', descKh: 'ត្រឡប់តម្លៃផ្សេងប្រសិនបើ #N/A', example: '=IFNA(VLOOKUP(A1,B:C,2,0), "Not found")', args: [{ name: 'value', desc: 'Expression to evaluate' }, { name: 'value_if_na', desc: 'Value to return on #N/A' }] },
  { name: 'SWITCH', category: 'Logical', syntax: 'SWITCH(expr, val1, result1, [val2, result2, ...], [default])', desc: 'Matches expression against values, returns corresponding result.', descKh: 'ប្រៀបធៀបតម្លៃ ត្រឡប់លទ្ធផលដែលត្រូវគ្នា', example: '=SWITCH(A1, 1,"Jan", 2,"Feb", "Other")', args: [{ name: 'expr', desc: 'Value to compare' }, { name: 'val1', desc: 'First match value' }, { name: 'result1', desc: 'Result if val1 matches' }] },

  // ---- Text ----
  { name: 'CONCAT', category: 'Text', syntax: 'CONCAT(text1, [text2, ...])', desc: 'Joins text strings together.', descKh: 'ភ្ជាប់អត្ថបទច្រើនជាអត្ថបទតែមួយ', example: '=CONCAT(A1, " ", B1)', args: [{ name: 'text1', desc: 'First text' }, { name: 'text2', desc: 'Additional text', optional: true }] },
  { name: 'CONCATENATE', category: 'Text', syntax: 'CONCATENATE(text1, [text2, ...])', desc: 'Joins text strings (legacy alias of CONCAT).', descKh: 'ភ្ជាប់អត្ថបទ (alias CONCAT)', example: '=CONCATENATE(A1, B1)', args: [{ name: 'text1', desc: 'First text' }] },
  { name: 'TEXTJOIN', category: 'Text', syntax: 'TEXTJOIN(delimiter, ignore_empty, text1, [text2, ...])', desc: 'Joins text with a delimiter, optionally skipping blanks.', descKh: 'ភ្ជាប់អត្ថបទដោយមានសញ្ញាបំបែក', example: '=TEXTJOIN(", ", TRUE, A1:A5)', args: [{ name: 'delimiter', desc: 'Separator text' }, { name: 'ignore_empty', desc: 'TRUE to skip blank cells' }, { name: 'text1', desc: 'Text or range' }] },
  { name: 'LEN', category: 'Text', syntax: 'LEN(text)', desc: 'Returns the number of characters.', descKh: 'ត្រឡប់ចំនួនតួអក្សរក្នុងអត្ថបទ', example: '=LEN("Hello")', args: [{ name: 'text', desc: 'The text string' }] },
  { name: 'LEFT', category: 'Text', syntax: 'LEFT(text, [num_chars])', desc: 'Returns leftmost characters from text.', descKh: 'ទាញតួអក្សរពីខាងឆ្វេង', example: '=LEFT("Hello", 3)', args: [{ name: 'text', desc: 'The text' }, { name: 'num_chars', desc: 'Characters to extract (default 1)', optional: true }] },
  { name: 'RIGHT', category: 'Text', syntax: 'RIGHT(text, [num_chars])', desc: 'Returns rightmost characters from text.', descKh: 'ទាញតួអក្សរពីខាងស្ដាំ', example: '=RIGHT("Hello", 2)', args: [{ name: 'text', desc: 'The text' }, { name: 'num_chars', desc: 'Characters to extract (default 1)', optional: true }] },
  { name: 'MID', category: 'Text', syntax: 'MID(text, start, num_chars)', desc: 'Returns characters from the middle of text.', descKh: 'ទាញតួអក្សរពីផ្នែកណាមួយក្នុងអត្ថបទ', example: '=MID("Hello World", 7, 5)', args: [{ name: 'text', desc: 'The text' }, { name: 'start', desc: '1-based start position' }, { name: 'num_chars', desc: 'Number of characters' }] },
  { name: 'UPPER', category: 'Text', syntax: 'UPPER(text)', desc: 'Converts text to uppercase.', descKh: 'បំប្លែងអត្ថបទជាអក្សរធំទាំងអស់', example: '=UPPER("hello")', args: [{ name: 'text', desc: 'The text' }] },
  { name: 'LOWER', category: 'Text', syntax: 'LOWER(text)', desc: 'Converts text to lowercase.', descKh: 'បំប្លែងអត្ថបទជាអក្សរតូចទាំងអស់', example: '=LOWER("HELLO")', args: [{ name: 'text', desc: 'The text' }] },
  { name: 'PROPER', category: 'Text', syntax: 'PROPER(text)', desc: 'Capitalizes the first letter of each word.', descKh: 'ធ្វើអក្សរធំដើមពាក្យ', example: '=PROPER("hello world")', args: [{ name: 'text', desc: 'The text' }] },
  { name: 'TRIM', category: 'Text', syntax: 'TRIM(text)', desc: 'Removes extra spaces from text.', descKh: 'លប់ចន្លោះលើក និងខ្ចៅ', example: '=TRIM("  hello  ")', args: [{ name: 'text', desc: 'The text' }] },
  { name: 'CLEAN', category: 'Text', syntax: 'CLEAN(text)', desc: 'Removes non-printable characters.', descKh: 'លប់តួអក្សរដែលមើលមិនឃើញ', example: '=CLEAN(A1)', args: [{ name: 'text', desc: 'The text' }] },
  { name: 'SUBSTITUTE', category: 'Text', syntax: 'SUBSTITUTE(text, old_text, new_text, [instance])', desc: 'Replaces occurrences of a substring.', descKh: 'ជំនួសអត្ថបទរងក្នុងអត្ថបទ', example: '=SUBSTITUTE("Hello World", "World", "Prism")', args: [{ name: 'text', desc: 'Original text' }, { name: 'old_text', desc: 'Text to replace' }, { name: 'new_text', desc: 'Replacement text' }, { name: 'instance', desc: 'Which occurrence (default all)', optional: true }] },
  { name: 'REPLACE', category: 'Text', syntax: 'REPLACE(text, start, num_chars, new_text)', desc: 'Replaces part of text by position.', descKh: 'ជំនួសអត្ថបទតាមទីតាំង', example: '=REPLACE("Hello", 2, 3, "XY")', args: [{ name: 'text', desc: 'Original text' }, { name: 'start', desc: '1-based start position' }, { name: 'num_chars', desc: 'Characters to replace' }, { name: 'new_text', desc: 'Replacement text' }] },
  { name: 'FIND', category: 'Text', syntax: 'FIND(find_text, within_text, [start])', desc: 'Case-sensitive position of substring (1-based).', descKh: 'ស្វែងរកទីតាំងអត្ថបទ (ប្រកបអក្សរ)', example: '=FIND("o", "Hello")', args: [{ name: 'find_text', desc: 'Text to find' }, { name: 'within_text', desc: 'Text to search in' }, { name: 'start', desc: 'Start position (default 1)', optional: true }] },
  { name: 'SEARCH', category: 'Text', syntax: 'SEARCH(find_text, within_text, [start])', desc: 'Case-insensitive search with wildcards.', descKh: 'ស្វែងរកអត្ថបទ (មិនប្រកបអក្សរ, wildcard *?)', example: '=SEARCH("h*o", "Hello")', args: [{ name: 'find_text', desc: 'Text to find (wildcards ok)' }, { name: 'within_text', desc: 'Text to search in' }, { name: 'start', desc: 'Start position', optional: true }] },
  { name: 'TEXT', category: 'Text', syntax: 'TEXT(value, format)', desc: 'Formats a number as text.', descKh: 'ធ្វើទ្រង់ទ្រាយចំនួនជាអត្ថបទ', example: '=TEXT(1234.5, "$0,000.00")', args: [{ name: 'value', desc: 'The number to format' }, { name: 'format', desc: 'Format string e.g. "0.00"' }] },
  { name: 'VALUE', category: 'Text', syntax: 'VALUE(text)', desc: 'Converts text to a number.', descKh: 'បំប្លែងអត្ថបទជាចំនួន', example: '=VALUE("123.45")', args: [{ name: 'text', desc: 'Text representing a number' }] },
  { name: 'REPT', category: 'Text', syntax: 'REPT(text, number)', desc: 'Repeats text a given number of times.', descKh: 'ធ្វើឡើងវិញអត្ថបទ n ដង', example: '=REPT("*", 5)', args: [{ name: 'text', desc: 'Text to repeat' }, { name: 'number', desc: 'Number of repetitions' }] },
  { name: 'CHAR', category: 'Text', syntax: 'CHAR(number)', desc: 'Returns the character for an ASCII code.', descKh: 'ត្រឡប់តួអក្សររបស់ ASCII code', example: '=CHAR(65)', args: [{ name: 'number', desc: 'ASCII code 1–255' }] },
  { name: 'CODE', category: 'Text', syntax: 'CODE(text)', desc: 'Returns the ASCII code of the first character.', descKh: 'ត្រឡប់ ASCII code នៃតួអក្សរទី១', example: '=CODE("A")', args: [{ name: 'text', desc: 'The text string' }] },
  { name: 'UNICHAR', category: 'Text', syntax: 'UNICHAR(number)', desc: 'Returns the Unicode character for a code point.', descKh: 'ត្រឡប់តួអក្សរ Unicode (ក, ខ, ℃ …)', example: '=UNICHAR(6082)', args: [{ name: 'number', desc: 'Unicode code point' }] },
  { name: 'UNICODE', category: 'Text', syntax: 'UNICODE(text)', desc: 'Returns the Unicode code point of the first character.', descKh: 'ត្រឡប់ Unicode code point នៃតួអក្សរទី១', example: '=UNICODE("ក")', args: [{ name: 'text', desc: 'The text string' }] },
  { name: 'EXACT', category: 'Text', syntax: 'EXACT(text1, text2)', desc: 'Returns TRUE if two strings are exactly equal (case-sensitive).', descKh: 'ត្រឡប់ TRUE ប្រសិនបើអត្ថបទស្មើ (ប្រកបអក្សរ)', example: '=EXACT("Hello", "hello")', args: [{ name: 'text1', desc: 'First text' }, { name: 'text2', desc: 'Second text' }] },
  { name: 'DOLLAR', category: 'Text', syntax: 'DOLLAR(number, [decimals])', desc: 'Formats a number as currency text.', descKh: 'ធ្វើទ្រង់ទ្រាយចំនួនជារូបិយប័ណ្ណ $', example: '=DOLLAR(1234.567, 2)', args: [{ name: 'number', desc: 'The amount' }, { name: 'decimals', desc: 'Decimal places (default 2)', optional: true }] },
  { name: 'NUMBERTEXT', category: 'Text', syntax: 'NUMBERTEXT(number)', desc: 'Converts a number to its English word form.', descKh: 'បំប្លែងចំនួនជាពាក្យ (ជាភាសាអង់គ្លេស)', example: '=NUMBERTEXT(42)', args: [{ name: 'number', desc: 'The number (integer)' }] },
  { name: 'T', category: 'Text', syntax: 'T(value)', desc: 'Returns the value if it is text, otherwise empty string.', descKh: 'ត្រឡប់អត្ថបទ ឬ "" ប្រសិនបើមិនមែនជាអត្ថបទ', example: '=T(A1)', args: [{ name: 'value', desc: 'The value to test' }] },

  // ---- Date & Time ----
  { name: 'TODAY', category: 'Date & Time', syntax: 'TODAY()', desc: "Returns today's date.", descKh: 'ត្រឡប់កាលបរិច្ឆេទថ្ងៃនេះ', example: '=TODAY()', args: [] },
  { name: 'NOW', category: 'Date & Time', syntax: 'NOW()', desc: 'Returns the current date and time.', descKh: 'ត្រឡប់ថ្ងៃ និងម៉ោងបច្ចុប្បន្ន', example: '=NOW()', args: [] },
  { name: 'DATE', category: 'Date & Time', syntax: 'DATE(year, month, day)', desc: 'Creates a date from year, month, and day.', descKh: 'បង្កើតថ្ងៃពីឆ្នាំ ខែ ថ្ងៃ', example: '=DATE(2026, 5, 19)', args: [{ name: 'year', desc: 'Four-digit year' }, { name: 'month', desc: '1–12' }, { name: 'day', desc: '1–31' }] },
  { name: 'YEAR', category: 'Date & Time', syntax: 'YEAR(date)', desc: 'Returns the year of a date.', descKh: 'ទាញឆ្នាំពីកាលបរិច្ឆេទ', example: '=YEAR(TODAY())', args: [{ name: 'date', desc: 'A date value' }] },
  { name: 'MONTH', category: 'Date & Time', syntax: 'MONTH(date)', desc: 'Returns the month (1–12) of a date.', descKh: 'ទាញខែ (1–12) ពីកាលបរិច្ឆេទ', example: '=MONTH(TODAY())', args: [{ name: 'date', desc: 'A date value' }] },
  { name: 'DAY', category: 'Date & Time', syntax: 'DAY(date)', desc: 'Returns the day of the month (1–31).', descKh: 'ទាញថ្ងៃ (1–31) ពីកាលបរិច្ឆេទ', example: '=DAY(TODAY())', args: [{ name: 'date', desc: 'A date value' }] },
  { name: 'WEEKDAY', category: 'Date & Time', syntax: 'WEEKDAY(date, [type])', desc: 'Returns the day of the week as a number.', descKh: 'ត្រឡប់ថ្ងៃប្រចាំសប្ដាហ៍ (1–7)', example: '=WEEKDAY(TODAY(), 2)', args: [{ name: 'date', desc: 'A date value' }, { name: 'type', desc: '1=Sun-Sat, 2=Mon-Sun', optional: true }] },
  { name: 'WEEKNUM', category: 'Date & Time', syntax: 'WEEKNUM(date)', desc: 'Returns the week number of the year.', descKh: 'ត្រឡប់លេខសប្ដាហ៍ក្នុងឆ្នាំ', example: '=WEEKNUM(TODAY())', args: [{ name: 'date', desc: 'A date value' }] },
  { name: 'ISOWEEKNUM', category: 'Date & Time', syntax: 'ISOWEEKNUM(date)', desc: 'Returns the ISO 8601 week number.', descKh: 'ត្រឡប់លេខសប្ដាហ៍ ISO 8601', example: '=ISOWEEKNUM(TODAY())', args: [{ name: 'date', desc: 'A date value' }] },
  { name: 'HOUR', category: 'Date & Time', syntax: 'HOUR(time)', desc: 'Returns the hour (0–23) from a time.', descKh: 'ទាញម៉ោង (0–23) ពីម៉ោង', example: '=HOUR(NOW())', args: [{ name: 'time', desc: 'A time or datetime value' }] },
  { name: 'MINUTE', category: 'Date & Time', syntax: 'MINUTE(time)', desc: 'Returns the minute (0–59).', descKh: 'ទាញនាទី (0–59) ពីម៉ោង', example: '=MINUTE(NOW())', args: [{ name: 'time', desc: 'A time or datetime value' }] },
  { name: 'SECOND', category: 'Date & Time', syntax: 'SECOND(time)', desc: 'Returns the second (0–59).', descKh: 'ទាញវិនាទី (0–59) ពីម៉ោង', example: '=SECOND(NOW())', args: [{ name: 'time', desc: 'A time or datetime value' }] },
  { name: 'TIME', category: 'Date & Time', syntax: 'TIME(hour, minute, second)', desc: 'Creates a time string from components.', descKh: 'បង្កើតម៉ោងពី ម៉ោង នាទី វិនាទី', example: '=TIME(14, 30, 0)', args: [{ name: 'hour', desc: '0–23' }, { name: 'minute', desc: '0–59' }, { name: 'second', desc: '0–59' }] },
  { name: 'EDATE', category: 'Date & Time', syntax: 'EDATE(start_date, months)', desc: 'Returns a date N months from a start date.', descKh: 'ត្រឡប់ថ្ងៃ N ខែពីថ្ងៃចាប់ផ្ដើម', example: '=EDATE(TODAY(), 3)', args: [{ name: 'start_date', desc: 'The start date' }, { name: 'months', desc: 'Months to add (negative = before)' }] },
  { name: 'EOMONTH', category: 'Date & Time', syntax: 'EOMONTH(start_date, months)', desc: 'Returns the last day of the month N months away.', descKh: 'ត្រឡប់ថ្ងៃចុងខែ N ខែ', example: '=EOMONTH(TODAY(), 0)', args: [{ name: 'start_date', desc: 'The start date' }, { name: 'months', desc: 'Months offset' }] },
  { name: 'DATEDIF', category: 'Date & Time', syntax: 'DATEDIF(start_date, end_date, unit)', desc: 'Returns the difference between two dates.', descKh: 'ត្រឡប់ចំនួនឆ្នាំ/ខែ/ថ្ងៃ រវាងថ្ងៃពីរ', example: '=DATEDIF(A1, TODAY(), "Y")', args: [{ name: 'start_date', desc: 'Start date' }, { name: 'end_date', desc: 'End date' }, { name: 'unit', desc: '"Y" years, "M" months, "D" days' }] },
  { name: 'DAYS', category: 'Date & Time', syntax: 'DAYS(end_date, start_date)', desc: 'Returns the number of days between two dates.', descKh: 'ត្រឡប់ចំនួនថ្ងៃរវាងថ្ងៃពីរ', example: '=DAYS(TODAY(), A1)', args: [{ name: 'end_date', desc: 'End date' }, { name: 'start_date', desc: 'Start date' }] },
  { name: 'DAYS360', category: 'Date & Time', syntax: 'DAYS360(start_date, end_date, [method])', desc: 'Days between dates on a 360-day year.', descKh: 'ថ្ងៃរវាងថ្ងៃពីរ (ឆ្នាំ 360 ថ្ងៃ)', example: '=DAYS360(A1, B1)', args: [{ name: 'start_date', desc: 'Start date' }, { name: 'end_date', desc: 'End date' }, { name: 'method', desc: 'FALSE=US, TRUE=European', optional: true }] },
  { name: 'WORKDAY', category: 'Date & Time', syntax: 'WORKDAY(start_date, days)', desc: 'Returns a date N working days from start.', descKh: 'ត្រឡប់ថ្ងៃ N ថ្ងៃធ្វើការ (ដោយមិនរាប់ចុងសប្ដាហ៍)', example: '=WORKDAY(TODAY(), 10)', args: [{ name: 'start_date', desc: 'Start date' }, { name: 'days', desc: 'Working days to add' }] },
  { name: 'NETWORKDAYS', category: 'Date & Time', syntax: 'NETWORKDAYS(start_date, end_date)', desc: 'Returns the number of working days between dates.', descKh: 'ចំនួនថ្ងៃធ្វើការ រវាងថ្ងៃពីរ', example: '=NETWORKDAYS(A1, B1)', args: [{ name: 'start_date', desc: 'Start date' }, { name: 'end_date', desc: 'End date' }] },
  { name: 'DATEVALUE', category: 'Date & Time', syntax: 'DATEVALUE(date_text)', desc: 'Converts a date text string to a serial number.', descKh: 'បំប្លែងអត្ថបទថ្ងៃជាលេខ serial', example: '=DATEVALUE("2026-05-19")', args: [{ name: 'date_text', desc: 'Date as text "YYYY-MM-DD"' }] },
  { name: 'TIMEVALUE', category: 'Date & Time', syntax: 'TIMEVALUE(time_text)', desc: 'Converts a time text string to a decimal.', descKh: 'បំប្លែងអត្ថបទម៉ោងជាលេខ decimal', example: '=TIMEVALUE("14:30:00")', args: [{ name: 'time_text', desc: 'Time as text "HH:MM:SS"' }] },

  // ---- Lookup ----
  { name: 'VLOOKUP', category: 'Lookup', syntax: 'VLOOKUP(lookup, table, col_index, [range_lookup])', desc: 'Searches first column of a table and returns a value.', descKh: 'ស្វែងរកក្នុងជួរឈរទី១ ត្រឡប់តម្លៃក្នុងជួរ', example: '=VLOOKUP(A1, B:D, 2, FALSE)', args: [{ name: 'lookup', desc: 'Value to search for' }, { name: 'table', desc: 'Table range' }, { name: 'col_index', desc: '1-based column to return' }, { name: 'range_lookup', desc: 'FALSE for exact match', optional: true }] },
  { name: 'HLOOKUP', category: 'Lookup', syntax: 'HLOOKUP(lookup, table, row_index, [range_lookup])', desc: 'Searches first row of a table and returns a value.', descKh: 'ស្វែងរកក្នុងជួរដេកទី១ ត្រឡប់តម្លៃ', example: '=HLOOKUP(A1, B1:D3, 2, FALSE)', args: [{ name: 'lookup', desc: 'Value to search for' }, { name: 'table', desc: 'Table range' }, { name: 'row_index', desc: '1-based row to return' }, { name: 'range_lookup', desc: 'FALSE for exact match', optional: true }] },
  { name: 'XLOOKUP', category: 'Lookup', syntax: 'XLOOKUP(lookup, lookup_array, return_array, [if_not_found], [match_mode])', desc: 'Modern replacement for VLOOKUP — search any range.', descKh: 'ជំនួស VLOOKUP ទំនើប — ស្វែងរកជួរណាមួយ', example: '=XLOOKUP(A1, B:B, C:C, "Not found")', args: [{ name: 'lookup', desc: 'Value to find' }, { name: 'lookup_array', desc: 'Range to search' }, { name: 'return_array', desc: 'Range to return from' }, { name: 'if_not_found', desc: 'Value if no match', optional: true }, { name: 'match_mode', desc: '0=exact, -1=next smaller, 1=next larger, 2=wildcard', optional: true }] },
  { name: 'INDEX', category: 'Lookup', syntax: 'INDEX(array, row, [col])', desc: 'Returns the value at a given row and column in a range.', descKh: 'ត្រឡប់តម្លៃតាមជួរ និងជួរឈរ', example: '=INDEX(A1:C10, 3, 2)', args: [{ name: 'array', desc: 'The range' }, { name: 'row', desc: '1-based row number' }, { name: 'col', desc: '1-based column number', optional: true }] },
  { name: 'MATCH', category: 'Lookup', syntax: 'MATCH(lookup, array, [match_type])', desc: 'Returns the position of an item in a range.', descKh: 'ត្រឡប់ទីតាំងទំនាក់ទំនងនៃធាតុ', example: '=MATCH("Alice", A:A, 0)', args: [{ name: 'lookup', desc: 'Value to find' }, { name: 'array', desc: 'Range to search' }, { name: 'match_type', desc: '0=exact, 1=largest≤, -1=smallest≥', optional: true }] },
  { name: 'XMATCH', category: 'Lookup', syntax: 'XMATCH(lookup, array, [match_mode])', desc: 'Modern MATCH with flexible match modes.', descKh: 'ជំនួស MATCH ទំនើប ជម្រើសស្វែងរកច្រើន', example: '=XMATCH("Alice", A:A)', args: [{ name: 'lookup', desc: 'Value to find' }, { name: 'array', desc: 'Range to search' }, { name: 'match_mode', desc: '0=exact, -1=smaller, 1=larger, 2=wildcard', optional: true }] },
  { name: 'OFFSET', category: 'Lookup', syntax: 'OFFSET(reference, rows, cols, [height], [width])', desc: 'Returns a reference shifted from a starting cell.', descKh: 'ត្រឡប់ក្រឡាដែលផ្លាស់ទីពីក្រឡាចាប់ផ្ដើម', example: '=OFFSET(A1, 2, 1)', args: [{ name: 'reference', desc: 'Starting cell' }, { name: 'rows', desc: 'Rows to shift' }, { name: 'cols', desc: 'Cols to shift' }, { name: 'height', desc: 'Height of returned range', optional: true }, { name: 'width', desc: 'Width', optional: true }] },
  { name: 'INDIRECT', category: 'Lookup', syntax: 'INDIRECT(ref_text)', desc: 'Returns the reference specified by a text string.', descKh: 'ត្រឡប់ការយោងដែលបញ្ជាក់ដោយអត្ថបទ', example: '=INDIRECT("A1")', args: [{ name: 'ref_text', desc: 'A cell address as text e.g. "A1"' }] },
  { name: 'CHOOSE', category: 'Lookup', syntax: 'CHOOSE(index, val1, [val2, ...])', desc: 'Returns a value from a list based on index.', descKh: 'ត្រឡប់តម្លៃពីបញ្ជីតាមលេខលំដាប់', example: '=CHOOSE(2, "a","b","c")', args: [{ name: 'index', desc: '1-based position' }, { name: 'val1', desc: 'First choice' }, { name: 'val2', desc: 'More choices', optional: true }] },
  { name: 'ROW', category: 'Lookup', syntax: 'ROW([reference])', desc: 'Returns the row number of a cell.', descKh: 'ត្រឡប់លេខជួរដេករបស់ក្រឡា', example: '=ROW()', args: [{ name: 'reference', desc: 'Cell reference', optional: true }] },
  { name: 'COLUMN', category: 'Lookup', syntax: 'COLUMN([reference])', desc: 'Returns the column number of a cell.', descKh: 'ត្រឡប់លេខជួរឈររបស់ក្រឡា', example: '=COLUMN()', args: [{ name: 'reference', desc: 'Cell reference', optional: true }] },
  { name: 'ROWS', category: 'Lookup', syntax: 'ROWS(range)', desc: 'Returns the number of rows in a range.', descKh: 'ត្រឡប់ចំនួនជួរដេកក្នុងជួរ', example: '=ROWS(A1:A10)', args: [{ name: 'range', desc: 'The range' }] },
  { name: 'COLUMNS', category: 'Lookup', syntax: 'COLUMNS(range)', desc: 'Returns the number of columns in a range.', descKh: 'ត្រឡប់ចំនួនជួរឈរក្នុងជួរ', example: '=COLUMNS(A1:D1)', args: [{ name: 'range', desc: 'The range' }] },
  { name: 'ADDRESS', category: 'Lookup', syntax: 'ADDRESS(row, col, [abs_type])', desc: 'Returns a cell address as text.', descKh: 'ត្រឡប់អាសយដ្ឋានក្រឡាជាអត្ថបទ', example: '=ADDRESS(1, 1)', args: [{ name: 'row', desc: '1-based row' }, { name: 'col', desc: '1-based column' }, { name: 'abs_type', desc: '1=$A$1, 4=A1', optional: true }] },

  // ---- Conditional ----
  { name: 'SUMIF', category: 'Conditional', syntax: 'SUMIF(range, criterion, [sum_range])', desc: 'Sums cells that meet a condition.', descKh: 'បូកសរុបក្រឡាដែលបំពេញលក្ខខណ្ឌ', example: '=SUMIF(A:A, ">100", B:B)', args: [{ name: 'range', desc: 'Range to check' }, { name: 'criterion', desc: 'Condition e.g. ">100"' }, { name: 'sum_range', desc: 'Range to sum', optional: true }] },
  { name: 'SUMIFS', category: 'Conditional', syntax: 'SUMIFS(sum_range, range1, crit1, [range2, crit2, ...])', desc: 'Sums cells meeting multiple conditions.', descKh: 'បូកសរុបក្រឡាដែលបំពេញលក្ខខណ្ឌច្រើន', example: '=SUMIFS(C:C, A:A, "Yes", B:B, ">0")', args: [{ name: 'sum_range', desc: 'Range to sum' }, { name: 'range1', desc: 'First criteria range' }, { name: 'crit1', desc: 'First criterion' }] },
  { name: 'COUNTIF', category: 'Conditional', syntax: 'COUNTIF(range, criterion)', desc: 'Counts cells that meet a condition.', descKh: 'រាប់ក្រឡាដែលបំពេញលក្ខខណ្ឌ', example: '=COUNTIF(A:A, "Yes")', args: [{ name: 'range', desc: 'Range to check' }, { name: 'criterion', desc: 'Condition' }] },
  { name: 'COUNTIFS', category: 'Conditional', syntax: 'COUNTIFS(range1, crit1, [range2, crit2, ...])', desc: 'Counts cells meeting multiple conditions.', descKh: 'រាប់ក្រឡាដែលបំពេញលក្ខខណ្ឌច្រើន', example: '=COUNTIFS(A:A, "Yes", B:B, ">0")', args: [{ name: 'range1', desc: 'First criteria range' }, { name: 'crit1', desc: 'First criterion' }] },
  { name: 'AVERAGEIF', category: 'Conditional', syntax: 'AVERAGEIF(range, criterion, [average_range])', desc: 'Averages cells that meet a condition.', descKh: 'រករាប់មធ្យមក្រឡាដែលបំពេញលក្ខខណ្ឌ', example: '=AVERAGEIF(A:A, ">0", B:B)', args: [{ name: 'range', desc: 'Range to check' }, { name: 'criterion', desc: 'Condition' }, { name: 'average_range', desc: 'Range to average', optional: true }] },
  { name: 'AVERAGEIFS', category: 'Conditional', syntax: 'AVERAGEIFS(avg_range, range1, crit1, [range2, crit2, ...])', desc: 'Averages cells meeting multiple conditions.', descKh: 'រករាប់មធ្យមក្រឡាដែលបំពេញលក្ខខណ្ឌច្រើន', example: '=AVERAGEIFS(C:C, A:A, "Yes", B:B, ">0")', args: [{ name: 'avg_range', desc: 'Range to average' }, { name: 'range1', desc: 'First criteria range' }, { name: 'crit1', desc: 'First criterion' }] },
  { name: 'MAXIFS', category: 'Conditional', syntax: 'MAXIFS(max_range, range1, crit1, [range2, crit2, ...])', desc: 'Returns maximum value from cells meeting conditions.', descKh: 'ត្រឡប់តម្លៃធំបំផុតក្នុងក្រឡាដែលបំពេញលក្ខខណ្ឌ', example: '=MAXIFS(C:C, A:A, "Yes")', args: [{ name: 'max_range', desc: 'Range to find max in' }, { name: 'range1', desc: 'Criteria range' }, { name: 'crit1', desc: 'Criterion' }] },
  { name: 'MINIFS', category: 'Conditional', syntax: 'MINIFS(min_range, range1, crit1, [range2, crit2, ...])', desc: 'Returns minimum value from cells meeting conditions.', descKh: 'ត្រឡប់តម្លៃតូចបំផុតក្នុងក្រឡាដែលបំពេញលក្ខខណ្ឌ', example: '=MINIFS(C:C, A:A, "Yes")', args: [{ name: 'min_range', desc: 'Range to find min in' }, { name: 'range1', desc: 'Criteria range' }, { name: 'crit1', desc: 'Criterion' }] },

  // ---- Statistical ----
  { name: 'MEDIAN', category: 'Statistical', syntax: 'MEDIAN(number1, [number2, ...])', desc: 'Returns the middle value of a dataset.', descKh: 'ត្រឡប់តម្លៃកណ្ដាលនៃទិន្នន័យ', example: '=MEDIAN(A1:A10)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'STDEV', category: 'Statistical', syntax: 'STDEV(number1, [number2, ...])', desc: 'Returns the sample standard deviation.', descKh: 'ត្រឡប់គម្លាតស្ដង់ដារ (គំរូ)', example: '=STDEV(A1:A20)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'STDEVP', category: 'Statistical', syntax: 'STDEVP(number1, [number2, ...])', desc: 'Returns the population standard deviation.', descKh: 'ត្រឡប់គម្លាតស្ដង់ដារ (ប្រជាជន)', example: '=STDEVP(A1:A20)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'VAR', category: 'Statistical', syntax: 'VAR(number1, [number2, ...])', desc: 'Returns the sample variance.', descKh: 'ត្រឡប់វ៉ារ្យ៉ង់ (គំរូ)', example: '=VAR(A1:A20)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'VARP', category: 'Statistical', syntax: 'VARP(number1, [number2, ...])', desc: 'Returns the population variance.', descKh: 'ត្រឡប់វ៉ារ្យ៉ង់ (ប្រជាជន)', example: '=VARP(A1:A20)', args: [{ name: 'number1', desc: 'First number or range' }] },
  { name: 'LARGE', category: 'Statistical', syntax: 'LARGE(range, k)', desc: 'Returns the k-th largest value.', descKh: 'ត្រឡប់តម្លៃធំទី k', example: '=LARGE(A1:A10, 2)', args: [{ name: 'range', desc: 'The data range' }, { name: 'k', desc: 'Rank (1 = largest)' }] },
  { name: 'SMALL', category: 'Statistical', syntax: 'SMALL(range, k)', desc: 'Returns the k-th smallest value.', descKh: 'ត្រឡប់តម្លៃតូចទី k', example: '=SMALL(A1:A10, 2)', args: [{ name: 'range', desc: 'The data range' }, { name: 'k', desc: 'Rank (1 = smallest)' }] },
  { name: 'RANK', category: 'Statistical', syntax: 'RANK(number, ref, [order])', desc: 'Returns the rank of a number in a list.', descKh: 'ត្រឡប់លំដាប់ចំណាត់ថ្នាក់នៃចំនួន', example: '=RANK(A1, A1:A10)', args: [{ name: 'number', desc: 'The number to rank' }, { name: 'ref', desc: 'The range of numbers' }, { name: 'order', desc: '0=desc (default), 1=asc', optional: true }] },
  { name: 'PERCENTILE', category: 'Statistical', syntax: 'PERCENTILE(range, k)', desc: 'Returns the k-th percentile (k: 0 to 1).', descKh: 'ត្រឡប់ percentile ទី k', example: '=PERCENTILE(A1:A10, 0.9)', args: [{ name: 'range', desc: 'The data range' }, { name: 'k', desc: 'Percentile 0 to 1' }] },

  // ---- Financial ----
  { name: 'PMT', category: 'Financial', syntax: 'PMT(rate, nper, pv, [fv], [type])', desc: 'Returns the periodic payment for a loan.', descKh: 'គណនាការទូទាត់ប្រចាំខែ (កម្ចី)', example: '=PMT(0.05/12, 60, -10000)', args: [{ name: 'rate', desc: 'Interest rate per period' }, { name: 'nper', desc: 'Total number of periods' }, { name: 'pv', desc: 'Present value (loan, negative)' }, { name: 'fv', desc: 'Future value', optional: true }, { name: 'type', desc: '0=end, 1=beginning', optional: true }] },
  { name: 'FV', category: 'Financial', syntax: 'FV(rate, nper, pmt, [pv], [type])', desc: 'Returns the future value of an investment.', descKh: 'ត្រឡប់តម្លៃអនាគតនៃការវិនិយោគ', example: '=FV(0.05/12, 60, -200)', args: [{ name: 'rate', desc: 'Interest rate per period' }, { name: 'nper', desc: 'Number of periods' }, { name: 'pmt', desc: 'Payment each period' }, { name: 'pv', desc: 'Present value', optional: true }, { name: 'type', desc: '0=end, 1=beginning', optional: true }] },
  { name: 'PV', category: 'Financial', syntax: 'PV(rate, nper, pmt, [fv], [type])', desc: 'Returns the present value of an investment.', descKh: 'ត្រឡប់តម្លៃបច្ចុប្បន្ននៃការវិនិយោគ', example: '=PV(0.05/12, 60, -200)', args: [{ name: 'rate', desc: 'Interest rate per period' }, { name: 'nper', desc: 'Number of periods' }, { name: 'pmt', desc: 'Payment each period' }, { name: 'fv', desc: 'Future value', optional: true }, { name: 'type', desc: '0=end, 1=beginning', optional: true }] },
  { name: 'NPV', category: 'Financial', syntax: 'NPV(rate, value1, [value2, ...])', desc: 'Returns the net present value of cash flows.', descKh: 'ត្រឡប់តម្លៃបច្ចុប្បន្នសុទ្ធ (NPV)', example: '=NPV(0.1, -1000, 300, 400, 500)', args: [{ name: 'rate', desc: 'Discount rate per period' }, { name: 'value1', desc: 'First cash flow' }, { name: 'value2', desc: 'Additional cash flows', optional: true }] },
  { name: 'IRR', category: 'Financial', syntax: 'IRR(values, [guess])', desc: 'Returns the internal rate of return.', descKh: 'ត្រឡប់អត្រាប្រាក់ចំណូលខាងក្នុង (IRR)', example: '=IRR(A1:A6)', args: [{ name: 'values', desc: 'Range of cash flows' }, { name: 'guess', desc: 'Initial guess (default 0.1)', optional: true }] },

  // ---- Info ----
  { name: 'ISBLANK', category: 'Info', syntax: 'ISBLANK(value)', desc: 'Returns TRUE if the cell is empty.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើក្រឡាទទេ', example: '=ISBLANK(A1)', args: [{ name: 'value', desc: 'The value or cell to test' }] },
  { name: 'ISNUMBER', category: 'Info', syntax: 'ISNUMBER(value)', desc: 'Returns TRUE if the value is a number.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើជាចំនួន', example: '=ISNUMBER(A1)', args: [{ name: 'value', desc: 'The value to test' }] },
  { name: 'ISTEXT', category: 'Info', syntax: 'ISTEXT(value)', desc: 'Returns TRUE if the value is text.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើជាអត្ថបទ', example: '=ISTEXT(A1)', args: [{ name: 'value', desc: 'The value to test' }] },
  { name: 'ISERROR', category: 'Info', syntax: 'ISERROR(value)', desc: 'Returns TRUE if the value is any error.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើជា error', example: '=ISERROR(A1/0)', args: [{ name: 'value', desc: 'The value to test' }] },
  { name: 'ISNA', category: 'Info', syntax: 'ISNA(value)', desc: 'Returns TRUE if the value is #N/A.', descKh: 'ត្រឡប់ TRUE ប្រសិនបើជា #N/A', example: '=ISNA(VLOOKUP(A1,B:C,2,0))', args: [{ name: 'value', desc: 'The value to test' }] },
  { name: 'TYPE', category: 'Info', syntax: 'TYPE(value)', desc: 'Returns a number indicating data type (1=number, 2=text, 4=boolean, 16=error).', descKh: 'ត្រឡប់ប្រភេទទិន្នន័យ (1=លេខ 2=អត្ថបទ 4=boolean 16=error)', example: '=TYPE(A1)', args: [{ name: 'value', desc: 'The value' }] },
  { name: 'N', category: 'Info', syntax: 'N(value)', desc: 'Converts a value to a number.', descKh: 'បំប្លែងតម្លៃជាចំនួន', example: '=N(TRUE)', args: [{ name: 'value', desc: 'The value to convert' }] },
];

export const FN_CATEGORIES: FnCategory[] = [
  'Math', 'Logical', 'Text', 'Date & Time', 'Lookup', 'Conditional', 'Statistical', 'Financial', 'Info',
];

export const FN_BY_CATEGORY = FN_CATEGORIES.reduce<Record<FnCategory, FnDef[]>>(
  (acc, cat) => ({ ...acc, [cat]: FUNCTION_REGISTRY.filter((f) => f.category === cat) }),
  {} as Record<FnCategory, FnDef[]>,
);
