import 'server-only';

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';
import { localAttachmentDir } from '@/env';

/**
 * Where the development driver keeps bytes.
 *
 * Only reached when R2 is not configured (`objectStore().kind === 'local'`).
 * Production never runs a line of this file — but a developer and the e2e suite
 * do, on every upload, so it is written as though it were reachable: a key is
 * mapped to a path under one directory and nowhere else, checked rather than
 * assumed.
 */

/**
 * A storage key is `w/<workspace>/a/<attachment>`, both uuids, and this is the
 * one place it becomes a filesystem path.
 *
 * Two defences rather than one. The character class rejects anything that is
 * not a uuid-shaped segment, so `..` never survives it; and the resolved path
 * is then checked to be inside the root, so a future change to that class
 * cannot quietly turn into a traversal. The keys are generated by
 * `storageKey()` and never by a user — this is what keeps that true even if one
 * day they are not.
 */
function pathFor(key: string): string {
  if (!/^[A-Za-z0-9][A-Za-z0-9/_-]*$/.test(key) || key.includes('//')) {
    throw new Error('Refusing a storage key that is not a plain path.');
  }

  const root = resolve(localAttachmentDir());
  const path = resolve(join(root, ...key.split('/')));

  if (path !== root && !path.startsWith(root + sep)) {
    throw new Error('Refusing a storage key that escapes the attachment directory.');
  }

  return path;
}

export async function writeLocalObject(key: string, bytes: Uint8Array): Promise<void> {
  const path = pathFor(key);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes);
}

/** Null when the bytes are not there — an upload that was never completed. */
/**
 * Remove one object (§20.9's sweeper).
 *
 * A missing file is success, not an error: the sweeper is at-least-once by
 * design — it may run twice over the same row after a crash between the delete
 * and the commit — and a second pass over bytes that are already gone is the
 * ordinary case rather than a fault.
 */
export async function deleteLocalObject(key: string): Promise<void> {
  await rm(pathFor(key), { force: true });
}

export async function readLocalObject(key: string): Promise<Buffer | null> {
  try {
    return await readFile(pathFor(key));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
    throw error;
  }
}
