import type { ReportElement, ReportPage, ReportTemplate } from '@/schemas/report';
import { PAGE_CANVAS_SIZES } from '@/schemas/report';

// ReportPage extended with auto-layout tracking field
type AutoPage = ReportPage & { sourceTableId?: string };

// ── Row-fit helpers ───────────────────────────────────────────────────────────

function calcRowsFit(el: ReportElement): number {
  return calcRowsFitH(el, el.h);
}

function calcRowsFitH(el: ReportElement, h: number): number {
  const p = (el.props ?? {}) as Record<string, unknown>;
  const hPy     = (p.headerPaddingY as number) ?? 8;
  const hFs     = (p.headerFontSize as number) ?? (p.fontSize as number) ?? 12;
  const cPy     = (p.cellPaddingY as number)   ?? 6;
  const fs      = (p.fontSize as number)       ?? 12;
  const urlBarH = p.dataSource ? 22 : 0;
  const headerH = hPy * 2 + hFs + 2;
  const rowH    = cPy * 2 + fs  + 2;
  return Math.max(1, Math.floor((h - headerH - urlBarH) / rowH));
}

// Natural height of the last continuation table (header + N rows).
// The last continuation has no overflow indicator, so we don't add the indicator height.
function calcLastContH(el: ReportElement, rowCount: number): number {
  const p = (el.props ?? {}) as Record<string, unknown>;
  const hPy     = (p.headerPaddingY as number) ?? 8;
  const hFs     = (p.headerFontSize as number) ?? (p.fontSize as number) ?? 12;
  const cPy     = (p.cellPaddingY as number)   ?? 6;
  const fs      = (p.fontSize as number)       ?? 12;
  const urlBarH = p.dataSource ? 22 : 0;
  const headerH = hPy * 2 + hFs + 2;
  const rowH    = cPy * 2 + fs  + 2;
  return headerH + urlBarH + rowCount * rowH;
}

// ── Signature for change-detection ───────────────────────────────────────────
// Uses the *effective* original height (autoOriginalH ?? el.h) so the sig stays
// stable after a stretch is applied, preventing infinite re-layout loops.

export function autoLayoutSig(elements: ReportElement[], canvasH = 0, marginTop = 0, marginBottom = 0): string {
  return `${canvasH}|${marginTop}|${marginBottom}|` + elements
    .filter((el) => {
      const p = (el.props ?? {}) as Record<string, unknown>;
      return (
        el.type === 'table' &&
        p.autoPageBreak &&
        !p.isContinuation &&
        !p.autoGenerated
      );
    })
    .map((el) => {
      const p = (el.props ?? {}) as Record<string, unknown>;
      const rows       = (p.rows as unknown[]) ?? [];
      const effectiveH = (p.autoOriginalH as number | undefined) ?? el.h;
      return `${el.id}|${effectiveH}|${el.y}|${rows.length}|${el.page ?? 0}|${!!p.autoPageBreak}`;
    })
    .join('::');
}

// ── Main function ─────────────────────────────────────────────────────────────

export function computeAutoLayout(
  template: ReportTemplate,
  fitHints?: Record<string, number>,
): { pages: ReportPage[]; elements: ReportElement[] } | null {
  // Derive canvas height from the template's page-size / orientation
  const ps           = PAGE_CANVAS_SIZES[template.pageSize] ?? PAGE_CANVAS_SIZES.A4;
  const canvasH      = template.orientation === 'landscape' ? ps.w : ps.h;
  const marginTop    = template.margins?.top    ?? 0;
  const marginBottom = template.margins?.bottom ?? 0;

  const originalPages    = (
    template.pages?.length ? template.pages : [{ id: 'page-0' }]
  ) as AutoPage[];
  const originalElements = template.elements ?? [];

  // Source tables: non-continuation, non-auto-generated, with autoPageBreak on
  const autoTables = originalElements.filter((el) => {
    const p = (el.props ?? {}) as Record<string, unknown>;
    return (
      el.type === 'table' &&
      p.autoPageBreak &&
      !p.isContinuation &&
      !p.autoGenerated
    );
  });

  if (autoTables.length === 0) return null;

  let workPages    = [...originalPages] as AutoPage[];
  let workElements = [...originalElements];

  for (const tableEl of autoTables) {
    const tableId = tableEl.id;

    // ── 1. Restore previously auto-moved elements (page + y) ──────────────
    workElements = workElements.map((el) => {
      const p = (el.props ?? {}) as Record<string, unknown>;
      if (p.autoMovedFromTableId === tableId && p.autoMovedFromPage !== undefined) {
        const { autoMovedFromPage, autoMovedFromTableId, autoMovedOriginalY, ...restProps } = p;
        return {
          ...el,
          page: autoMovedFromPage as number,
          y:    autoMovedOriginalY !== undefined ? (autoMovedOriginalY as number) : el.y,
          props: restProps,
        };
      }
      return el;
    });

    // ── 2. Remove auto-generated content; restore original table height ────
    const autoPageIdxs = new Set<number>();
    workPages.forEach((pg, i) => {
      if (pg.sourceTableId === tableId) autoPageIdxs.add(i);
    });

    workElements = workElements.filter((el) => {
      const p = (el.props ?? {}) as Record<string, unknown>;
      return !(p.autoGenerated && p.sourceTableId === tableId);
    });

    // Restore original h (saved as autoOriginalH) and clear pagination props
    workElements = workElements.map((el) => {
      if (el.id !== tableId) return el;
      const p = (el.props ?? {}) as Record<string, unknown>;
      const { endRow: _e, autoOriginalH, ...restProps } = p;
      return {
        ...el,
        h:     autoOriginalH !== undefined ? (autoOriginalH as number) : el.h,
        props: restProps,
      };
    });

    // Remove auto-generated pages and re-index remaining elements
    if (autoPageIdxs.size > 0) {
      const keptIdxs = workPages.map((_, i) => i).filter((i) => !autoPageIdxs.has(i));
      const oldToNew = new Map(keptIdxs.map((oldI, newI) => [oldI, newI]));
      workPages       = workPages.filter((_, i) => !autoPageIdxs.has(i));
      workElements    = workElements.map((el) => ({
        ...el,
        page: oldToNew.get(el.page ?? 0) ?? (el.page ?? 0),
      }));
    }

    // ── 3. Re-fetch table after mutations ────────────────────────────────────
    const tEl = workElements.find((el) => el.id === tableId);
    if (!tEl) continue;

    const p          = tEl.props as Record<string, unknown>;
    const allRows    = (p.rows as Record<string, unknown>[]) ?? [];
    const sourcePage = tEl.page ?? 0;

    // ── 3.5. Overflow check against the ORIGINAL (restored) height ───────────
    //  Case 1 — no overflow: nothing to do.
    //  Use the DOM-measured hint when available — formula underestimates row heights
    //  for multi-line text, causing rows to silently clip instead of paginating.
    const origTableH  = tEl.h;
    const hintFit     = fitHints?.[tableId];
    const origRowsFit = hintFit ?? calcRowsFit(tEl);

    // ── Special case: DOM hint says ALL rows fit ──────────────────────────────
    //  The underflow detection in element-table.tsx can raise hintFit to
    //  allRows.length when it finds the formula over-estimated row height.
    //  In that situation we still want to stretch the element (so it fills the
    //  page and the guard `autoOriginalH !== undefined` stays satisfied for
    //  future DOM measurements), but we must NOT set an endRow or create any
    //  continuation pages — every row is shown on the source page.
    if (hintFit !== undefined && hintFit >= allRows.length) {
      // Fill the full page canvas — do NOT subtract marginBottom here.
      // Row stretching (perRowH in element-table.tsx + PDF generator) distributes
      // content within the element so rows never enter the margin area, while the
      // element boundary itself reaching canvasH eliminates the blank gap below the
      // indicator that was visible in the design canvas.
      const stretchedHFull = Math.max(origTableH, canvasH - tEl.y);
      if (stretchedHFull > origTableH) {
        // Re-apply stretch so the element fills the page and autoOriginalH is set.
        workElements = workElements.map((el) =>
          el.id === tableId
            ? { ...el, h: stretchedHFull, props: { ...el.props, autoOriginalH: origTableH } }
            : el,
        );
        // Move any below-table elements to a new page (same logic as Case 2).
        const origTableBottom2 = tEl.y + origTableH;
        const belowIdsFull = new Set(
          workElements
            .filter(
              (el) =>
                (el.page ?? 0) === sourcePage &&
                el.id !== tableId &&
                el.y >= origTableBottom2,
            )
            .map((el) => el.id),
        );
        if (belowIdsFull.size > 0) {
          const insertIdx = sourcePage + 1;
          workPages = [
            ...workPages.slice(0, insertIdx),
            {
              id:            `al-${tableId}-p${insertIdx}`,
              background:    workPages[sourcePage]?.background,
              sourceTableId: tableId,
            } as AutoPage,
            ...workPages.slice(insertIdx),
          ];
          workElements = workElements.map((el) => {
            if (belowIdsFull.has(el.id)) return el;
            const elPage = el.page ?? 0;
            return elPage >= insertIdx ? { ...el, page: elPage + 1 } : el;
          });
          workElements = workElements.map((el) => {
            if (!belowIdsFull.has(el.id)) return el;
            const gap = Math.max(0, el.y - origTableBottom2);
            return {
              ...el,
              page:  insertIdx,
              y:     marginTop + gap,
              props: {
                ...el.props,
                autoMovedFromPage:    sourcePage,
                autoMovedFromTableId: tableId,
                autoMovedOriginalY:   el.y,
              },
            };
          });
        }
      }
      continue; // no endRow, no continuation pages
    }

    if (allRows.length <= origRowsFit) continue;

    // Has overflow → stretch table to fill the full page canvas.
    // Do NOT subtract marginBottom: row stretching (perRowH) distributes content
    // within the element height so rows stay above the indicator and never bleed
    // into the margin area.  Subtracting marginBottom used to leave a visible blank
    // strip below the indicator in the design canvas (the gap the user reported).
    const stretchedH  = Math.max(origTableH, canvasH - tEl.y);
    const IND         = 24; // overflow indicator height (shown on non-final pages in editor)
    const CONT_BADGE  = 20; // "Continued from previous page" badge at top of continuation pages

    // Use DOM-measured fit when available; derive average row height for continuation pages.
    // Use (stretchedH - marginBottom - IND) as the content-only height so the formula
    // doesn't count the margin area as available row space.
    const rowsFit = hintFit ?? calcRowsFitH(tEl, stretchedH - marginBottom - IND);

    // Compute average actual row height from the hint so continuation pages use
    // the same (measured) row height instead of the formula single-line estimate.
    // Subtract marginBottom here so the estimate reflects only the content area —
    // stretchedH now reaches canvasH (full page), but row content still stops at
    // canvasH - marginBottom (just before the bottom margin).
    const hintedAvgRowH: number | null = (() => {
      if (hintFit == null || hintFit <= 0) return null;
      const pp      = tEl.props as Record<string, unknown>;
      const hPy     = (pp.headerPaddingY as number) ?? 8;
      const hFs     = (pp.headerFontSize as number) ?? (pp.fontSize as number) ?? 12;
      const urlBarH = pp.dataSource ? 22 : 0;
      const headerH = hPy * 2 + hFs + 2;
      return (stretchedH - marginBottom - IND - headerH - urlBarH) / hintFit;
    })();

    const contPageH   = canvasH - marginTop - marginBottom;                // usable height per continuation page
    const contRowsFit = hintedAvgRowH != null
      ? (() => {
          const pp      = tEl.props as Record<string, unknown>;
          const hPy     = (pp.headerPaddingY as number) ?? 8;
          const hFs     = (pp.headerFontSize as number) ?? (pp.fontSize as number) ?? 12;
          const urlBarH = pp.dataSource ? 22 : 0;
          const headerH = hPy * 2 + hFs + 2;
          return Math.max(1, Math.floor((contPageH - CONT_BADGE - IND - headerH - urlBarH) / hintedAvgRowH!));
        })()
      : calcRowsFitH(tEl, contPageH - CONT_BADGE - IND);

    // Apply stretch, saving original h for restoration (step 2 of future runs)
    workElements = workElements.map((el) =>
      el.id === tableId
        ? { ...el, h: stretchedH, props: { ...el.props, autoOriginalH: origTableH } }
        : el,
    );

    const updatedTEl     = workElements.find((el) => el.id === tableId)!;
    const origTableBottom = tEl.y + origTableH;

    // Elements below the ORIGINAL table bottom (y >= origTableBottom) will be migrated
    const belowIds = new Set(
      workElements
        .filter(
          (el) =>
            (el.page ?? 0) === sourcePage &&
            el.id !== tableId &&
            el.y >= origTableBottom,
        )
        .map((el) => el.id),
    );

    // ── Case 2: all rows fit in the stretched table ───────────────────────────
    //  Stretch covers page 1. Move elements below to a new page inserted right
    //  after the source page so the continuation stays adjacent to the table.
    if (allRows.length <= rowsFit) {
      if (belowIds.size > 0) {
        const insertIdx = sourcePage + 1;
        workPages = [
          ...workPages.slice(0, insertIdx),
          {
            id:            `al-${tableId}-p${insertIdx}`,
            background:    workPages[sourcePage]?.background,
            sourceTableId: tableId,
          } as AutoPage,
          ...workPages.slice(insertIdx),
        ];
        // Shift page indices for elements on pages that moved back
        workElements = workElements.map((el) => {
          if (belowIds.has(el.id)) return el;
          const elPage = el.page ?? 0;
          return elPage >= insertIdx ? { ...el, page: elPage + 1 } : el;
        });
        workElements = workElements.map((el) => {
          if (!belowIds.has(el.id)) return el;
          const gap  = Math.max(0, el.y - origTableBottom);
          return {
            ...el,
            page:  insertIdx,
            y:     marginTop + gap,
            props: {
              ...el.props,
              autoMovedFromPage:    sourcePage,
              autoMovedFromTableId: tableId,
              autoMovedOriginalY:   el.y,
            },
          };
        });
      }
      continue; // no continuation table needed
    }

    // ── Case 3: still overflow after stretch → create continuation pages ─────
    //  Set endRow on original table to show only the rows that fit
    workElements = workElements.map((el) =>
      el.id === tableId
        ? { ...el, props: { ...el.props, endRow: rowsFit } }
        : el,
    );

    // ── 5. Build continuation slices ─────────────────────────────────────────
    //  Each continuation is inserted right after the source page so that
    //  continuation pages appear immediately after the table, before any other
    //  pages the user placed later in the report.
    let sliceStart     = rowsFit;
    let lastNewPageIdx = sourcePage;
    let lastSliceStart = rowsFit;
    let insertedCount  = 0;

    while (sliceStart < allRows.length) {
      lastSliceStart     = sliceStart;
      const isLast       = sliceStart + contRowsFit >= allRows.length;
      const sliceEnd     = isLast ? undefined : sliceStart + contRowsFit;
      const insertIdx    = sourcePage + 1 + insertedCount;

      // Shrink each continuation slice to its natural content height to avoid
      // a large blank gap at the bottom of continuation pages.
      let thisContH = contPageH;
      const pp      = tEl.props as Record<string, unknown>;
      const hPy     = (pp.headerPaddingY as number) ?? 8;
      const hFs     = (pp.headerFontSize as number) ?? (pp.fontSize as number) ?? 12;
      const urlBarH = pp.dataSource ? 22 : 0;
      const headerH = hPy * 2 + hFs + 2;
      if (isLast) {
        const lastRowCount = allRows.length - sliceStart;
        if (hintedAvgRowH != null) {
          thisContH = Math.min(contPageH, CONT_BADGE + headerH + urlBarH + lastRowCount * hintedAvgRowH);
        } else {
          thisContH = Math.min(contPageH, CONT_BADGE + calcLastContH(updatedTEl, lastRowCount));
        }
      } else if (hintedAvgRowH != null) {
        // Non-last page: use estimated natural content height to avoid empty space
        // at the bottom. IND = 24px indicator badge shown on non-last cont pages.
        const IND = 24;
        thisContH = Math.min(contPageH, CONT_BADGE + urlBarH + headerH + contRowsFit * hintedAvgRowH + IND);
      }
      // else: no DOM measurement yet → fill the full page (contPageH)

      workPages = [
        ...workPages.slice(0, insertIdx),
        {
          id:            `al-${tableId}-r${sliceStart}`,
          background:    workPages[sourcePage]?.background,
          sourceTableId: tableId,
        } as AutoPage,
        ...workPages.slice(insertIdx),
      ];

      // Shift page indices for elements displaced by the insertion
      workElements = workElements.map((el) => {
        if (el.id === tableId) return el; // original table stays on its page
        const elPage = el.page ?? 0;
        return elPage >= insertIdx ? { ...el, page: elPage + 1 } : el;
      });

      workElements = [
        ...workElements,
        {
          ...updatedTEl,
          id:    `al-${tableId}-r${sliceStart}`,
          page:  insertIdx,
          y:     marginTop,      // respect the page top margin
          h:     thisContH,      // natural height for last slice; full page for others
          props: {
            ...updatedTEl.props,
            startRow:       sliceStart,
            endRow:         sliceEnd,
            isContinuation: true,
            autoGenerated:  true,
            sourceTableId:  tableId,
          },
        },
      ];

      lastNewPageIdx = insertIdx;
      insertedCount++;
      sliceStart     = sliceEnd ?? allRows.length;
    }

    // ── 6. Move below-table elements to the last continuation page ────────────
    if (belowIds.size > 0) {
      const lastBatchCount   = allRows.length - lastSliceStart;
      // Use measured average row height for more accurate placement of below-elements.
      const lastContContentH = hintedAvgRowH != null
        ? (() => {
            const pp      = updatedTEl.props as Record<string, unknown>;
            const hPy     = (pp.headerPaddingY as number) ?? 8;
            const hFs     = (pp.headerFontSize as number) ?? (pp.fontSize as number) ?? 12;
            const urlBarH = pp.dataSource ? 22 : 0;
            const headerH = hPy * 2 + hFs + 2;
            return CONT_BADGE + headerH + urlBarH + lastBatchCount * hintedAvgRowH!;
          })()
        : calcLastContH(updatedTEl, lastBatchCount);

      workElements = workElements.map((el) => {
        if (!belowIds.has(el.id)) return el;
        const gap  = Math.max(0, el.y - origTableBottom);
        const newY = marginTop + lastContContentH + gap;
        return {
          ...el,
          page:  lastNewPageIdx,
          y:     newY,
          props: {
            ...el.props,
            autoMovedFromPage:    sourcePage,
            autoMovedFromTableId: tableId,
            autoMovedOriginalY:   el.y,
          },
        };
      });
    }
  }

  // Skip onChange when nothing actually changed (prevents spurious dirty flag on load)
  const pagesEq =
    workPages.length === originalPages.length &&
    workPages.every((pg, i) => JSON.stringify(pg) === JSON.stringify(originalPages[i]));
  const elsEq   =
    workElements.length === originalElements.length &&
    workElements.every((el, i) => JSON.stringify(el) === JSON.stringify(originalElements[i]));

  if (pagesEq && elsEq) return null;

  return { pages: workPages as ReportPage[], elements: workElements };
}

// ── Overflow signature for non-table elements ─────────────────────────────────

export function pageOverflowSig(
  elements: ReportElement[],
  template: ReportTemplate,
): string {
  const ps      = PAGE_CANVAS_SIZES[template.pageSize] ?? PAGE_CANVAS_SIZES.A4;
  const canvasH = template.orientation === 'landscape' ? ps.w : ps.h;
  return elements
    .filter((el) => {
      const p = (el.props ?? {}) as Record<string, unknown>;
      return !p.autoGenerated && el.y + el.h > canvasH + 5;
    })
    .map((el) => `${el.id}|${el.page ?? 0}|${el.y}|${el.h}`)
    .join('::');
}

// ── General element page-overflow handler ─────────────────────────────────────
// Moves any non-auto element whose bottom exceeds the canvas height to the next page.

export function computePageOverflow(
  template: ReportTemplate,
): { pages: ReportPage[]; elements: ReportElement[] } | null {
  const ps      = PAGE_CANVAS_SIZES[template.pageSize] ?? PAGE_CANVAS_SIZES.A4;
  const canvasH = template.orientation === 'landscape' ? ps.w : ps.h;

  const originalPages    = (template.pages?.length ? template.pages : [{ id: 'page-0' }]) as ReportPage[];
  const originalElements = template.elements ?? [];

  const overflowing = originalElements.filter((el) => {
    const p = (el.props ?? {}) as Record<string, unknown>;
    if (p.autoGenerated) return false;
    if (el.type === 'table' && p.autoPageBreak) return false;
    return el.y + el.h > canvasH + 5;
  });

  if (overflowing.length === 0) return null;

  let workPages    = [...originalPages];
  let workElements = [...originalElements];

  for (const el of overflowing) {
    const sourcePage    = el.page ?? 0;
    const targetPageIdx = sourcePage + 1;

    while (workPages.length <= targetPageIdx) {
      workPages = [
        ...workPages,
        {
          id:         `of-pg-${workPages.length}`,
          background: workPages[sourcePage]?.background,
        } as ReportPage,
      ];
    }

    const newY = Math.max(0, el.y - canvasH);
    workElements = workElements.map((e) =>
      e.id === el.id ? { ...e, page: targetPageIdx, y: newY } : e,
    );
  }

  const pagesEq =
    workPages.length === originalPages.length &&
    workPages.every((pg, i) => JSON.stringify(pg) === JSON.stringify(originalPages[i]));
  const elsEq   =
    workElements.length === originalElements.length &&
    workElements.every((e, i) => JSON.stringify(e) === JSON.stringify(originalElements[i]));

  if (pagesEq && elsEq) return null;
  return { pages: workPages as ReportPage[], elements: workElements };
}
